# Generated by Django 5.1.2 on 2024-10-14 03:36

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', banjo.models.StringField(default='')),
                ('hint', banjo.models.StringField(default='')),
                ('difficulty', banjo.models.IntegerField(default=0)),
                ('option_a', banjo.models.StringField(default='')),
                ('option_b', banjo.models.StringField(default='')),
                ('option_c', banjo.models.StringField(default='')),
                ('option_d', banjo.models.StringField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
