# Generated by Django 5.1.2 on 2024-10-15 07:01

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_question_difficulty_remove_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=banjo.models.StringField(default=''),
        ),
    ]
