# Generated by Django 5.1.2 on 2024-10-16 06:40

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_answered_correctly'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prize_money',
            field=banjo.models.IntegerField(default=0),
        ),
    ]
