# Generated by Django 5.1.2 on 2024-10-18 00:19

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_prize_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=banjo.models.StringField(default=''),
        ),
    ]
