# Generated by Django 5.1.2 on 2024-10-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
    ]
